GCC-10: enable -fcommon for linking
With GCC 10 -fno-common is enabled by default[0] which causes linking
problems that might look like this:

/usr/bin/ld: read.o:/home/n6tadam/projects/fvwm/fvwm3/fvwm/../libs/FScreen.h:169:
multiple definition of `randr_event';
menus.o:/home/n6tadam/projects/fvwm/fvwm3/fvwm/../libs/FScreen.h:169:
first defined here

To fix this properly, extern declarations will be required.  But for
now, just disable this.

Helps #119

[0] https://gcc.gnu.org/gcc-10/porting_to.html#common